{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Values.secretsName }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data:
  # Backend
  SECRET_KEY: {{ randAlphaNum 32 | b64enc | quote }}
  FIRST_SUPERUSER_PASSWORD: {{ randAlphaNum 32 | b64enc | quote }}
  SMTP_PASSWORD: {{ randAlphaNum 32 | b64enc | quote }}
  
  # Postgres
  POSTGRES_PASSWORD: {{ randAlphaNum 32 | b64enc | quote }}
  
  # PgAdmin
  PGADMIN_DEFAULT_PASSWORD: {{ randAlphaNum 32 | b64enc | quote }}

  # Mongo
  MONGO_PASSWORD: {{ randAlphaNum 32 | b64enc | quote }}
{{- end }}
